### PR TITLE
DIP xxxx - implicit conversion operators

### PR DESCRIPTION
**Pull request by Basile-z**
## Introduction

The implicit conversion operators are two new operator overloads allowing the
conversion from a custom type or to a custom type, in a clean way that doesn't
require the use of a `cast` or of a constructor.

## Two different forms of implicit conversions are handled

1. The compiler tries to convert a type to a custom type. This case is covered by `opImplicitThis`.
2. The compiler tries to extract a type from a custom type. This case is covered by `opImplicitCast`.

### 1. opImplicitThis

`opImplicitThis` is a member function template covariant with the prototype

```d
static typeof(this) opImplicitThis(RValueT)(auto ref RValueT rvalue);
```

- The return must be of the same type as the aggregate that implements the operator.
- The template type parameter is set by the compiler to rvalue type.

### 2. opImplicitCast

`opImplicitCast` is a member function template covariant with the prototype

```d
LvalueT opImplicitThis(LvalueT)();
```

- The return must be of the same type as the template type parameter.
- The template type parameter is the type of the lvalue that's tried to be assigned.
( + note about parameter of overload set...)

## Usages

  1. Alternative to the existing single alias this.
  2. Allow the equivalent of multiple alias this.
  3. Allow calling functions without using explicitly the constructor of a custom type.

## Best practices

It should always be possible to annotate the implicit conversion operators `@safe` and `nothrow`

When not possible for `opImplicitCast` then `opCast` should be prefered because
it's more clear in the code that something not regular is done if `cast` appears.

When not possible for `opImplicitThis` then a constructor should be used
to show what really happens.

( + something about the fact that it's user choice and was not an option taken in D
original design)

## Implementation

The implicit conversion operators are tried along with built-in attempts to
implicit conversion and before attempts on other operators such as `opCast`.

## Grammar changes

The grammar is not affected, this DIP strictly concerns the semantic.

## Breaking changes

Existing `opImplicitThis` or `opImplicitCast` functions will be tried in
a context not necessarily compatible with the current use.

Otherwise the implicit conversion operators are new and only tried when added explicitly so supporting them doesn't break any existing code.
However when adding them to existing types that already implemented other operator overloads then the type might behave differently.
In particular `opImplcitConvR` can predate `opCast` if one or more common types are covered.

## Notes

Although the semantic of operator overloads is used, implicit conversion has no operator,
it's not an expression on its own, it's rather a compilation process used in several contexts related to assignment.
It's more conveniant however to use the opXXXX syntax for the special functions.

## Example 1 : BitSet parameters

```d
enum Option
{
    o1 = 0b001,
    o2 = 0b010,
    o3 = 0b100,
}

struct BitSet(E) if (is(E == enum))
{
    E v;

    static typeof(this) opImplicitThis(T)(T t)
    {
        typeof(this) result;
        static if (is(T == E[]))
        {
            foreach(e; t)
                result.v |= e;
            return result;
        }
        else static if (is(T == E))
        {
            result.v |= t;
            return result;
        }
        else static assert(false);
    }

    // enforce using the struct as container for E combinations
    T opImplicitCast(T)() if (is(T == E))
    {
        static assert(false, "only use " ~ typeof(this).stringof ~ " as set");
    }
}

void doSomethingWithOptions(BitSet!Option set) {}

void main()
{
    // accepted by the compiler as...
    // with(Option) doSomethingWithOptions(BitSet!Option.opImplicitThis!(Option[])([o1, o2]));
    with(Option) doSomethingWithOptions([o1, o2]);
    version(none)
    {
        BitSet!Option set;
        Option e = set;  // Error: static assert:  "only use BitSet!(Option) as set"
    }
}

```

## Example 4 : A simple Sum Type

### CODE REVIEW

**Comment by Basile-z** [comment]
used during devel :

```d
module opImplicitConv;

import std.stdio;
/*version = OP_NOT_IMPL;*/

struct SomeType
{
    int v;
    string s;

    this(int v)             { this.v = v; }
    this(string s)          { this.s = s; }
    this(int v, string s)   { this.v = v; this.s = s; }

    /* Constructor form / used to assign to a lvalue.
       Mostly useful for function calls.                */
    static SomeType opImplicitConvL(T)(T t)
    {
        static if (is(T : int))
            return SomeType(t);
        else static if (is(T : string))
            return SomeType(t);
        else
            static assert(0, "cannot implicitly convert `" ~ T.stringof ~ " to `SomeType`");
    }

    /* Getter form / used to extract / used as a rvalue.
       Mostly useful for static polymorphism                */
    T opImplicitConvR(T)()
    {
        static if (is(T : int))
            return v;
        else static if (is(T : string))
            return s;
        else
            static assert(0, "cannot implicitly convert `SomeType` to `" ~ T.stringof ~ "`");
    }
}
void func1(SomeType value)  {  value.writeln(); }
void func2(int value)       {  value.writeln(); }
void func3(string value)    {  value.writeln(); }

unittest
{
    SomeType st = SomeType(42, "42");

    version (OP_NOT_IMPL) func1(SomeType.opImplicitConvL(1));
    else func1(1);

    version (OP_NOT_IMPL) func1(SomeType.opImplicitConvL("1"));
    else func1("1");

    version (OP_NOT_IMPL) func2(st.opImplicitConvR!int);
    else func2(st);

    version (OP_NOT_IMPL) int a = st.opImplicitConvR!int;
    else int a = st;

    version (OP_NOT_IMPL) string b = st.opImplicitConvR!string;
    else string b = st;
}
```

Not sure if more complex cases will work

**Comment by JinShil** [comment]
A couple things that crossed my mind when reading this:

1.  I too have been thinking about this.  I did a search on the forum and the term `opImplicitCast` provided the most hits:  https://forum.dlang.org/search?q=opImplicitCast&scope=forum  I, therefore, assume that the community will be biased towards `opImplicitCast`.  Also, `opCast` sets an existing precedent.

2.  The language already has `opCast` and it has no `R` or `L` variation.  Adding and `L` and `R` variation to this introduces and inconsistency in the language.  There are operator variations of the form `opBinary` and `opBinaryRight` for binary operators and the assignment operator, but not for `opCast`.

**Comment by JinShil** [comment]
3.  There may be an ambiguity with `opCast` when implicitly converting to `bool`.  See https://dlang.org/spec/operatoroverloading.html#boolean_operators  That will need to be addressed.  Perhaps emitting an ambiguity error if both are defined, or deprecating `opCast`'s special case for `bool`.

**Comment by Basile-z** [comment]
> I too have been thinking about this.

Yes I know. This work is inspired by your comments on the recent NG topic about multiple alias this. I used the pseudo `user1234` there. I believe that the variations are not needed but havent tried if this works already or not.

**Comment by Basile-z** [comment]
> The language already has opCast and it has no R or L variation

The L version is used for implicit construction. Look carefully at the examples : `opImplicitConvL` is `static`.
It's used to solve the case where people have to use the constructor of their custom type in a function call when using a value of the type that derived in the custom types, while passing directly the value is less verbose.

I think that what you are interested into is only `opImplicitConvR`, i.e the operator overload that has the same morphology as `opCast`.

**Comment by 12345swordy** [comment]
@JinShil @Basile-z  I don't mind spearheading the dip on this. The rules for implicit conversion must be stricter then the c++ equivalent, if the dip were to be accepted by walter.  That means not allowing implicit conversions in function arguments by default, nothrow by default, disallow explicit implementation if implicit implementation already exist, etc.

**Pull request closed without merging**
